name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install runtime dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install dev tools
        run: |
          pip install black ruff pytest

      - name: Ruff Lint
        run: ruff check .
        continue-on-error: true

      - name: Black Check
        run: black --check .
        continue-on-error: true

      - name: Run tests
        run: pytest -q

